### ISSUE TITLE
Adicionar um evento de submit

### ISSUE THREAD

**Issue by abnerborgonha** [wllysses/gitfolio#2]
Olá acho que uma boa ideia seria adicionar um evento de submit para poder capturar o evento de enter do teclado, assim podendo apenas digitar e dar enter para gerar o portifolio. Eu fiz o download do repo e fiz essa implementação se permitir que seja adicionado PRs de terceiros aqui posso enviar a melhoria!

Dês de já muito obrigado. E parabéns pelo projeto.

**Comment by wllysses** [comment]
Olá. Essa seria uma das próximas melhorias que iria fazer, mas já que fez sinta-se a vontade para abrir a PR. O projeto é totalmente open source!

**Comment by abnerborgonha** [comment]
Opa show! Já fiz a PR: https://github.com/wllysses/gitfolio/pull/4/files

**Comment by wllysses** [comment]
PR aceito!
